server:
  port: 8081
  servlet:
    context-path: /xb
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
#      additional-paths: src/main/java #重启目录
#      exclude: WEB-INF/**
#    freemarker:
#      cache: false    #页面不加载缓存，修改即时生效

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.shopping.Entity

 #分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
